### ISSUE TITLE
cgltf_result_invalid_json

### ISSUE THREAD

**Issue by TomClabault** [alipbcs/ZetaRay#19]
I ran [this bistro scene](https://mega.nz/file/clIxxRoS#QWhJPnvBPDFRczlrhkb2fhBkV48sSFuOPXBiY7f7V_Y) through the BCn compress  utility and then ran ZetaLab ../Assets/bistro_zeta.gltf but this yields the error:

![image](https://github.com/user-attachments/assets/d3c7c16e-d78a-4f2c-942c-0fe4db5c28ae)

Any ideas?

**Comment by TomClabault** [comment]
Trying to import bistro_zeta.gltf into Blender also fails:

![image](https://github.com/user-attachments/assets/ad15dd5c-db35-4555-a3c4-5215d45e56ce)

**Comment by alipbcs** [comment]
The problem was invalid image URIs in the converted gltf file. It only occured when the images were in a subdirectory ('./bistro-textures' in this case). It just so happened that all my test scenes had the images in the same directory as the gltf file, so I hadn't run into it before.

I pushed a fix. Let me know if the issue persists.

**Comment by TomClabault** [comment]
Fixed 👍
