### ISSUE TITLE
Launching Zetalab fails silently

### ISSUE THREAD

**Issue by Firesampo** [alipbcs/ZetaRay#5]
Hi,

I've now tried building & running this using two different machines (a really beefy NVidia A6000 desktop machine, and an RTX 2080 super laptop), without much success. I'm using VS 2022 version 17.5.2 and CMake  3.25.1.

On both machines I'm able to build the solution in VS 2022 without errors, but when I launch the Zetalab app using cornell box gltf as the test scene, it just flashes up for a half a sec (I can see an empty app frame for a while), and quits silently without any error.

I wonder if there's some step(s) that I'm doing wrong, or am I missing something? Can you share a build I could try?

**Comment by alipbcs** [comment]
Hi,

Since I can't reproduce the issue manually, I'll need more information to pinpoint the problem. Could you try building and running the project in debug mode? There are many assertions that are compiled out in the release build. If one of them is triggered, then I'll have a better idea of what's the issue. If this doesn't work, try adding a breakpoint in ZetaRay/Samples/ZetaLab/ZetaLab.cpp around line 53 (initialization) and step through the code to see where it fails.

I can share prebuilt binaries, but I doubt that would help; the issue seems to be something that's triggered under certain hardware setups.

**Comment by Firesampo** [comment]
Hmm, could it have sth to do with this?

![exception](https://github.com/alipbcs/ZetaRay/assets/75070888/1fa87690-d6c8-427c-a955-25eb96b58b57)

**Comment by alipbcs** [comment]
Glad to hear it's working!

SetStablePowerState() requires the machine to be in developer mode. I just realized that I'm assuming that to be true by default. I'll change it to off.
